# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['Application/launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Application/frontend', 'Application/frontend'),
        ('Organs', 'Organs'),
        ('Behaviour', 'Behaviour'),
        ('Info-organs', 'Info-organs'),
        ('src/atlas_voice_assistant', 'src/atlas_voice_assistant'),
        ('atlas.py', '.'),
        ('llm.py', '.'),
        ('Mic_Check.py', '.'),
    ],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.responses',
        'starlette.staticfiles',
        'starlette.websockets',
        'faster_whisper',
        'torch',
        'numpy',
        'sounddevice',
        'kokoro',
        'langchain',
        'langchain_core',
        'langchain_google_genai',
        'langchain_groq',
        'langchain_ollama',
        'google_genai',
        'openai',
        'ollama',
        'openwakeword',
        'phonemizer',
        'pyttsx3',
        'python_dotenv',
        'reportlab',
        'pydantic',
        'pydantic_core',
        'typing_extensions',
        'anyio',
        'sniffio',
        'h11',
        'httptools',
        'uvloop',
        'watchfiles',
        'websockets',
        'cffi',
        'cryptography',
        'certifi',
        'charset_normalizer',
        'idna',
        'requests',
        'urllib3',
        'click',
        'colorama',
        'setuptools',
        'packaging',
        'jaraco',
        'more_itertools',
        'zipp',
        'importlib_metadata',
        'platformdirs',
        'appdirs',
        'distlib',
        'filelock',
        'virtualenv',
        'pep517',
        'tomli',
        'tomli_w',
        'build',
        'wheel',
        'pip',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ATLAS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)